---

- name: Ensure configuration directory exists
  file:
    name: "{{ bigfix_client_conf_dir }}"
    state: directory

- name: Download the BigFix Client
  get_url:
    url: "{{ bigfix_client_file_url }}"
    dest: "/tmp/{{ bigfix_client_file_dest }}"
    checksum: "sha256:{{ bigfix_client_file_sum }}"

- include: "install/{{ ansible_os_family }}.yml"

- name: Record the installation
  file:
    dest: "{{ bigfix_client_conf_dir }}/.ansible_installed"
    state: touch